name: Release Workflow
on:
  release:
    types: [published]
jobs:
  build:
    name: release
    env:
      REF: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build --file ./build/Dockerfile \
            -t docker.pkg.github.com/jesse0michael/go-rest-assured/assured:${REF##*/} \
            -t docker.pkg.github.com/jesse0michael/go-rest-assured/assured .

      - name: Push
        run: |
          docker login docker.pkg.github.com -u Jesse0Michael -p ${{ secrets.PAT }}
          docker push docker.pkg.github.com/jesse0michael/go-rest-assured/assured:${REF##*/}
