name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: ridedott/release-me-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Build
        run: |
          docker build --file ./build/Dockerfile -t docker.pkg.github.com/jesse0michael/go-rest-assured/assured:${REF##*/} .

      - name: Push
        run: |
          docker login docker.pkg.github.com -u Jesse0Michael -p ${{ secrets.PAT }}
          docker push docker.pkg.github.com/jesse0michael/go-rest-assured/assured:${REF##*/}
